# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.models.single_raster_or_vector_operator import SingleRasterOrVectorOperator

class TestSingleRasterOrVectorOperator(unittest.TestCase):
    """SingleRasterOrVectorOperator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleRasterOrVectorOperator:
        """Test SingleRasterOrVectorOperator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleRasterOrVectorOperator`
        """
        model = SingleRasterOrVectorOperator()
        if include_optional:
            return SingleRasterOrVectorOperator(
                params = geoengine_openapi_client.models.raster_vector_join_parameters.RasterVectorJoinParameters(
                    feature_aggregation = null, 
                    feature_aggregation_ignore_no_data = True, 
                    names = null, 
                    temporal_aggregation = null, 
                    temporal_aggregation_ignore_no_data = True, ),
                sources = geoengine_openapi_client.models.single_vector_multiple_raster_sources.SingleVectorMultipleRasterSources(
                    rasters = [
                        null
                        ], 
                    vector = null, ),
                type = 'GdalSource'
            )
        else:
            return SingleRasterOrVectorOperator(
                params = geoengine_openapi_client.models.raster_vector_join_parameters.RasterVectorJoinParameters(
                    feature_aggregation = null, 
                    feature_aggregation_ignore_no_data = True, 
                    names = null, 
                    temporal_aggregation = null, 
                    temporal_aggregation_ignore_no_data = True, ),
                sources = geoengine_openapi_client.models.single_vector_multiple_raster_sources.SingleVectorMultipleRasterSources(
                    rasters = [
                        null
                        ], 
                    vector = null, ),
                type = 'GdalSource',
        )
        """

    def testSingleRasterOrVectorOperator(self):
        """Test SingleRasterOrVectorOperator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
