# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from geoengine_openapi_client.models.spatial_grid_descriptor import SpatialGridDescriptor  # noqa: E501

class TestSpatialGridDescriptor(unittest.TestCase):
    """SpatialGridDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpatialGridDescriptor:
        """Test SpatialGridDescriptor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpatialGridDescriptor`
        """
        model = SpatialGridDescriptor()  # noqa: E501
        if include_optional:
            return SpatialGridDescriptor(
                descriptor = 'source',
                spatial_grid = geoengine_openapi_client.models.spatial_grid_definition.SpatialGridDefinition(
                    geo_transform = geoengine_openapi_client.models.geo_transform.GeoTransform(
                        origin_coordinate = geoengine_openapi_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), 
                        x_pixel_size = 1.337, 
                        y_pixel_size = 1.337, ), 
                    grid_bounds = geoengine_openapi_client.models.grid_bounding_box2_d.GridBoundingBox2D(
                        bottom_right_idx = geoengine_openapi_client.models.grid_idx2_d.GridIdx2D(
                            x_idx = 56, 
                            y_idx = 56, ), 
                        top_left_idx = geoengine_openapi_client.models.grid_idx2_d.GridIdx2D(
                            x_idx = 56, 
                            y_idx = 56, ), ), )
            )
        else:
            return SpatialGridDescriptor(
                descriptor = 'source',
                spatial_grid = geoengine_openapi_client.models.spatial_grid_definition.SpatialGridDefinition(
                    geo_transform = geoengine_openapi_client.models.geo_transform.GeoTransform(
                        origin_coordinate = geoengine_openapi_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), 
                        x_pixel_size = 1.337, 
                        y_pixel_size = 1.337, ), 
                    grid_bounds = geoengine_openapi_client.models.grid_bounding_box2_d.GridBoundingBox2D(
                        bottom_right_idx = geoengine_openapi_client.models.grid_idx2_d.GridIdx2D(
                            x_idx = 56, 
                            y_idx = 56, ), 
                        top_left_idx = geoengine_openapi_client.models.grid_idx2_d.GridIdx2D(
                            x_idx = 56, 
                            y_idx = 56, ), ), ),
        )
        """

    def testSpatialGridDescriptor(self):
        """Test SpatialGridDescriptor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
