# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.models.symbology_raster import SymbologyRaster

class TestSymbologyRaster(unittest.TestCase):
    """SymbologyRaster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SymbologyRaster:
        """Test SymbologyRaster
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SymbologyRaster`
        """
        model = SymbologyRaster()
        if include_optional:
            return SymbologyRaster(
                opacity = 1.337,
                raster_colorizer = None,
                type = 'raster'
            )
        else:
            return SymbologyRaster(
                opacity = 1.337,
                raster_colorizer = None,
                type = 'raster',
        )
        """

    def testSymbologyRaster(self):
        """Test SymbologyRaster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
