# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.models.resource_layer_collection import ResourceLayerCollection

class TestResourceLayerCollection(unittest.TestCase):
    """ResourceLayerCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceLayerCollection:
        """Test ResourceLayerCollection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceLayerCollection`
        """
        model = ResourceLayerCollection()
        if include_optional:
            return ResourceLayerCollection(
                id = '',
                type = 'layerCollection'
            )
        else:
            return ResourceLayerCollection(
                id = '',
                type = 'layerCollection',
        )
        """

    def testResourceLayerCollection(self):
        """Test ResourceLayerCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
