# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.models.interpolation_resolution_one_of1 import InterpolationResolutionOneOf1

class TestInterpolationResolutionOneOf1(unittest.TestCase):
    """InterpolationResolutionOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InterpolationResolutionOneOf1:
        """Test InterpolationResolutionOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InterpolationResolutionOneOf1`
        """
        model = InterpolationResolutionOneOf1()
        if include_optional:
            return InterpolationResolutionOneOf1(
                type = 'fraction',
                x = 1.337,
                y = 1.337
            )
        else:
            return InterpolationResolutionOneOf1(
                type = 'fraction',
                x = 1.337,
                y = 1.337,
        )
        """

    def testInterpolationResolutionOneOf1(self):
        """Test InterpolationResolutionOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
