# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.8.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.models.ogr_source_time_format_one_of1 import OgrSourceTimeFormatOneOf1

class TestOgrSourceTimeFormatOneOf1(unittest.TestCase):
    """OgrSourceTimeFormatOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OgrSourceTimeFormatOneOf1:
        """Test OgrSourceTimeFormatOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OgrSourceTimeFormatOneOf1`
        """
        model = OgrSourceTimeFormatOneOf1()
        if include_optional:
            return OgrSourceTimeFormatOneOf1(
                format = 'unixTimeStamp',
                timestamp_type = 'epochSeconds'
            )
        else:
            return OgrSourceTimeFormatOneOf1(
                format = 'unixTimeStamp',
                timestamp_type = 'epochSeconds',
        )
        """

    def testOgrSourceTimeFormatOneOf1(self):
        """Test OgrSourceTimeFormatOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
