# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_openapi_client.api.ogc_api import OGCApi


class TestOGCApi(unittest.TestCase):
    """OGCApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OGCApi()

    def tearDown(self) -> None:
        pass

    def test_wcs_handler(self) -> None:
        """Test case for wcs_handler

        OGC WCS endpoint
        """
        pass

    def test_wfs_handler(self) -> None:
        """Test case for wfs_handler

        OGC WFS endpoint
        """
        pass

    def test_wms_handler(self) -> None:
        """Test case for wms_handler

        OGC WMS endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
