/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColorParamStatic
 */
export interface ColorParamStatic {
    /**
     * 
     * @type {Array<number>}
     * @memberof ColorParamStatic
     */
    color: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ColorParamStatic
     */
    type: ColorParamStaticTypeEnum;
}


/**
 * @export
 */
export const ColorParamStaticTypeEnum = {
    Static: 'static',
    Derived: 'derived'
} as const;
export type ColorParamStaticTypeEnum = typeof ColorParamStaticTypeEnum[keyof typeof ColorParamStaticTypeEnum];


/**
 * Check if a given object implements the ColorParamStatic interface.
 */
export function instanceOfColorParamStatic(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "color" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ColorParamStaticFromJSON(json: any): ColorParamStatic {
    return ColorParamStaticFromJSONTyped(json, false);
}

export function ColorParamStaticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorParamStatic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': json['color'],
        'type': json['type'],
    };
}

export function ColorParamStaticToJSON(value?: ColorParamStatic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'type': value.type,
    };
}

