/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Data1
 */
export interface Data1 {
    /**
     * 
     * @type {any}
     * @memberof Data1
     */
    data: any | null;
}

/**
 * Check if a given object implements the Data1 interface.
 */
export function instanceOfData1(value: object): value is Data1 {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function Data1FromJSON(json: any): Data1 {
    return Data1FromJSONTyped(json, false);
}

export function Data1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Data1 {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function Data1ToJSON(json: any): Data1 {
    return Data1ToJSONTyped(json, false);
}

export function Data1ToJSONTyped(value?: Data1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

