/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataUsage
 */
export interface DataUsage {
    /**
     * 
     * @type {string}
     * @memberof DataUsage
     */
    computationId: string;
    /**
     * 
     * @type {number}
     * @memberof DataUsage
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof DataUsage
     */
    data: string;
    /**
     * 
     * @type {Date}
     * @memberof DataUsage
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof DataUsage
     */
    userId: string;
}

/**
 * Check if a given object implements the DataUsage interface.
 */
export function instanceOfDataUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "computationId" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function DataUsageFromJSON(json: any): DataUsage {
    return DataUsageFromJSONTyped(json, false);
}

export function DataUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'computationId': json['computationId'],
        'count': json['count'],
        'data': json['data'],
        'timestamp': (new Date(json['timestamp'])),
        'userId': json['userId'],
    };
}

export function DataUsageToJSON(value?: DataUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'computationId': value.computationId,
        'count': value.count,
        'data': value.data,
        'timestamp': (value.timestamp.toISOString()),
        'userId': value.userId,
    };
}

