/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GdalDatasetParameters } from './GdalDatasetParameters';
import {
    GdalDatasetParametersFromJSON,
    GdalDatasetParametersFromJSONTyped,
    GdalDatasetParametersToJSON,
} from './GdalDatasetParameters';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';

/**
 * one temporal slice of the dataset that requires reading from exactly one Gdal dataset
 * @export
 * @interface GdalLoadingInfoTemporalSlice
 */
export interface GdalLoadingInfoTemporalSlice {
    /**
     * 
     * @type {number}
     * @memberof GdalLoadingInfoTemporalSlice
     */
    cacheTtl?: number;
    /**
     * 
     * @type {GdalDatasetParameters}
     * @memberof GdalLoadingInfoTemporalSlice
     */
    params?: GdalDatasetParameters;
    /**
     * 
     * @type {TimeInterval}
     * @memberof GdalLoadingInfoTemporalSlice
     */
    time: TimeInterval;
}

/**
 * Check if a given object implements the GdalLoadingInfoTemporalSlice interface.
 */
export function instanceOfGdalLoadingInfoTemporalSlice(value: object): boolean {
    if (!('time' in value)) return false;
    return true;
}

export function GdalLoadingInfoTemporalSliceFromJSON(json: any): GdalLoadingInfoTemporalSlice {
    return GdalLoadingInfoTemporalSliceFromJSONTyped(json, false);
}

export function GdalLoadingInfoTemporalSliceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalLoadingInfoTemporalSlice {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheTtl': json['cacheTtl'] == null ? undefined : json['cacheTtl'],
        'params': json['params'] == null ? undefined : GdalDatasetParametersFromJSON(json['params']),
        'time': TimeIntervalFromJSON(json['time']),
    };
}

export function GdalLoadingInfoTemporalSliceToJSON(value?: GdalLoadingInfoTemporalSlice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cacheTtl': value['cacheTtl'],
        'params': GdalDatasetParametersToJSON(value['params']),
        'time': TimeIntervalToJSON(value['time']),
    };
}

