/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GetCoverageRequest = {
    GetCoverage: 'GetCoverage'
} as const;
export type GetCoverageRequest = typeof GetCoverageRequest[keyof typeof GetCoverageRequest];


export function instanceOfGetCoverageRequest(value: any): boolean {
    for (const key in GetCoverageRequest) {
        if (Object.prototype.hasOwnProperty.call(GetCoverageRequest, key)) {
            if (GetCoverageRequest[key as keyof typeof GetCoverageRequest] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GetCoverageRequestFromJSON(json: any): GetCoverageRequest {
    return GetCoverageRequestFromJSONTyped(json, false);
}

export function GetCoverageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCoverageRequest {
    return json as GetCoverageRequest;
}

export function GetCoverageRequestToJSON(value?: GetCoverageRequest | null): any {
    return value as any;
}

export function GetCoverageRequestToJSONTyped(value: any, ignoreDiscriminator: boolean): GetCoverageRequest {
    return value as GetCoverageRequest;
}

