/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GetFeatureRequest = {
    GetFeature: 'GetFeature'
} as const;
export type GetFeatureRequest = typeof GetFeatureRequest[keyof typeof GetFeatureRequest];


export function instanceOfGetFeatureRequest(value: any): boolean {
    for (const key in GetFeatureRequest) {
        if (Object.prototype.hasOwnProperty.call(GetFeatureRequest, key)) {
            if (GetFeatureRequest[key as keyof typeof GetFeatureRequest] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GetFeatureRequestFromJSON(json: any): GetFeatureRequest {
    return GetFeatureRequestFromJSONTyped(json, false);
}

export function GetFeatureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeatureRequest {
    return json as GetFeatureRequest;
}

export function GetFeatureRequestToJSON(value?: GetFeatureRequest | null): any {
    return value as any;
}

export function GetFeatureRequestToJSONTyped(value: any, ignoreDiscriminator: boolean): GetFeatureRequest {
    return value as GetFeatureRequest;
}

