/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GridIdx2D } from './GridIdx2D';
import {
    GridIdx2DFromJSON,
    GridIdx2DFromJSONTyped,
    GridIdx2DToJSON,
} from './GridIdx2D';

/**
 * 
 * @export
 * @interface GridBoundingBox2D
 */
export interface GridBoundingBox2D {
    /**
     * 
     * @type {GridIdx2D}
     * @memberof GridBoundingBox2D
     */
    bottomRightIdx: GridIdx2D;
    /**
     * 
     * @type {GridIdx2D}
     * @memberof GridBoundingBox2D
     */
    topLeftIdx: GridIdx2D;
}

/**
 * Check if a given object implements the GridBoundingBox2D interface.
 */
export function instanceOfGridBoundingBox2D(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bottomRightIdx" in value;
    isInstance = isInstance && "topLeftIdx" in value;

    return isInstance;
}

export function GridBoundingBox2DFromJSON(json: any): GridBoundingBox2D {
    return GridBoundingBox2DFromJSONTyped(json, false);
}

export function GridBoundingBox2DFromJSONTyped(json: any, ignoreDiscriminator: boolean): GridBoundingBox2D {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bottomRightIdx': GridIdx2DFromJSON(json['bottomRightIdx']),
        'topLeftIdx': GridIdx2DFromJSON(json['topLeftIdx']),
    };
}

export function GridBoundingBox2DToJSON(value?: GridBoundingBox2D | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bottomRightIdx': GridIdx2DToJSON(value.bottomRightIdx),
        'topLeftIdx': GridIdx2DToJSON(value.topLeftIdx),
    };
}

