/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistogramBoundsOneOf
 */
export interface HistogramBoundsOneOf {
    /**
     * 
     * @type {any}
     * @memberof HistogramBoundsOneOf
     */
    data: any | null;
}

/**
 * Check if a given object implements the HistogramBoundsOneOf interface.
 */
export function instanceOfHistogramBoundsOneOf(value: object): value is HistogramBoundsOneOf {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HistogramBoundsOneOfFromJSON(json: any): HistogramBoundsOneOf {
    return HistogramBoundsOneOfFromJSONTyped(json, false);
}

export function HistogramBoundsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramBoundsOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function HistogramBoundsOneOfToJSON(json: any): HistogramBoundsOneOf {
    return HistogramBoundsOneOfToJSONTyped(json, false);
}

export function HistogramBoundsOneOfToJSONTyped(value?: HistogramBoundsOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

