/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistogramBoundsOneOf1Values } from './HistogramBoundsOneOf1Values';
import {
    HistogramBoundsOneOf1ValuesFromJSON,
    HistogramBoundsOneOf1ValuesFromJSONTyped,
    HistogramBoundsOneOf1ValuesToJSON,
    HistogramBoundsOneOf1ValuesToJSONTyped,
} from './HistogramBoundsOneOf1Values';

/**
 * 
 * @export
 * @interface HistogramBoundsOneOf1
 */
export interface HistogramBoundsOneOf1 {
    /**
     * 
     * @type {HistogramBoundsOneOf1Values}
     * @memberof HistogramBoundsOneOf1
     */
    values: HistogramBoundsOneOf1Values;
}

/**
 * Check if a given object implements the HistogramBoundsOneOf1 interface.
 */
export function instanceOfHistogramBoundsOneOf1(value: object): value is HistogramBoundsOneOf1 {
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function HistogramBoundsOneOf1FromJSON(json: any): HistogramBoundsOneOf1 {
    return HistogramBoundsOneOf1FromJSONTyped(json, false);
}

export function HistogramBoundsOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramBoundsOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'values': HistogramBoundsOneOf1ValuesFromJSON(json['values']),
    };
}

export function HistogramBoundsOneOf1ToJSON(json: any): HistogramBoundsOneOf1 {
    return HistogramBoundsOneOf1ToJSONTyped(json, false);
}

export function HistogramBoundsOneOf1ToJSONTyped(value?: HistogramBoundsOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': HistogramBoundsOneOf1ValuesToJSON(value['values']),
    };
}

