/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistogramBucketsOneOf1
 */
export interface HistogramBucketsOneOf1 {
    /**
     * 
     * @type {number}
     * @memberof HistogramBucketsOneOf1
     */
    maxNumberOfBuckets?: number;
    /**
     * 
     * @type {HistogramBucketsOneOf1TypeEnum}
     * @memberof HistogramBucketsOneOf1
     */
    type: HistogramBucketsOneOf1TypeEnum;
}


/**
 * @export
 */
export const HistogramBucketsOneOf1TypeEnum = {
    SquareRootChoiceRule: 'squareRootChoiceRule'
} as const;
export type HistogramBucketsOneOf1TypeEnum = typeof HistogramBucketsOneOf1TypeEnum[keyof typeof HistogramBucketsOneOf1TypeEnum];


/**
 * Check if a given object implements the HistogramBucketsOneOf1 interface.
 */
export function instanceOfHistogramBucketsOneOf1(value: object): value is HistogramBucketsOneOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function HistogramBucketsOneOf1FromJSON(json: any): HistogramBucketsOneOf1 {
    return HistogramBucketsOneOf1FromJSONTyped(json, false);
}

export function HistogramBucketsOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramBucketsOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'maxNumberOfBuckets': json['maxNumberOfBuckets'] == null ? undefined : json['maxNumberOfBuckets'],
        'type': json['type'],
    };
}

export function HistogramBucketsOneOf1ToJSON(json: any): HistogramBucketsOneOf1 {
    return HistogramBucketsOneOf1ToJSONTyped(json, false);
}

export function HistogramBucketsOneOf1ToJSONTyped(value?: HistogramBucketsOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxNumberOfBuckets': value['maxNumberOfBuckets'],
        'type': value['type'],
    };
}

