/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistogramBoundsOneOf1Values
 */
export interface HistogramBoundsOneOf1Values {
    /**
     * 
     * @type {number}
     * @memberof HistogramBoundsOneOf1Values
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof HistogramBoundsOneOf1Values
     */
    min: number;
}

/**
 * Check if a given object implements the HistogramBoundsOneOf1Values interface.
 */
export function instanceOfHistogramBoundsOneOf1Values(value: object): value is HistogramBoundsOneOf1Values {
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    return true;
}

export function HistogramBoundsOneOf1ValuesFromJSON(json: any): HistogramBoundsOneOf1Values {
    return HistogramBoundsOneOf1ValuesFromJSONTyped(json, false);
}

export function HistogramBoundsOneOf1ValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramBoundsOneOf1Values {
    if (json == null) {
        return json;
    }
    return {
        
        'max': json['max'],
        'min': json['min'],
    };
}

export function HistogramBoundsOneOf1ValuesToJSON(json: any): HistogramBoundsOneOf1Values {
    return HistogramBoundsOneOf1ValuesToJSONTyped(json, false);
}

export function HistogramBoundsOneOf1ValuesToJSONTyped(value?: HistogramBoundsOneOf1Values | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max': value['max'],
        'min': value['min'],
    };
}

