/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Explicit output resolution (`x`, `y`) in target coordinates.
 * @export
 * @interface InterpolationResolutionOneOf
 */
export interface InterpolationResolutionOneOf {
    /**
     * 
     * @type {InterpolationResolutionOneOfTypeEnum}
     * @memberof InterpolationResolutionOneOf
     */
    type: InterpolationResolutionOneOfTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof InterpolationResolutionOneOf
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof InterpolationResolutionOneOf
     */
    y: number;
}


/**
 * @export
 */
export const InterpolationResolutionOneOfTypeEnum = {
    Resolution: 'resolution'
} as const;
export type InterpolationResolutionOneOfTypeEnum = typeof InterpolationResolutionOneOfTypeEnum[keyof typeof InterpolationResolutionOneOfTypeEnum];


/**
 * Check if a given object implements the InterpolationResolutionOneOf interface.
 */
export function instanceOfInterpolationResolutionOneOf(value: object): value is InterpolationResolutionOneOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function InterpolationResolutionOneOfFromJSON(json: any): InterpolationResolutionOneOf {
    return InterpolationResolutionOneOfFromJSONTyped(json, false);
}

export function InterpolationResolutionOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterpolationResolutionOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'x': json['x'],
        'y': json['y'],
    };
}

export function InterpolationResolutionOneOfToJSON(json: any): InterpolationResolutionOneOf {
    return InterpolationResolutionOneOfToJSONTyped(json, false);
}

export function InterpolationResolutionOneOfToJSONTyped(value?: InterpolationResolutionOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'x': value['x'],
        'y': value['y'],
    };
}

