/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPolygon } from './MultiPolygon';
import {
    MultiPolygonFromJSON,
    MultiPolygonFromJSONTyped,
    MultiPolygonToJSON,
    MultiPolygonToJSONTyped,
} from './MultiPolygon';

/**
 * 
 * @export
 * @interface MultiPolygon1
 */
export interface MultiPolygon1 {
    /**
     * 
     * @type {MultiPolygon}
     * @memberof MultiPolygon1
     */
    multiPolygon: MultiPolygon;
}

/**
 * Check if a given object implements the MultiPolygon1 interface.
 */
export function instanceOfMultiPolygon1(value: object): value is MultiPolygon1 {
    if (!('multiPolygon' in value) || value['multiPolygon'] === undefined) return false;
    return true;
}

export function MultiPolygon1FromJSON(json: any): MultiPolygon1 {
    return MultiPolygon1FromJSONTyped(json, false);
}

export function MultiPolygon1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPolygon1 {
    if (json == null) {
        return json;
    }
    return {
        
        'multiPolygon': MultiPolygonFromJSON(json['MultiPolygon']),
    };
}

export function MultiPolygon1ToJSON(json: any): MultiPolygon1 {
    return MultiPolygon1ToJSONTyped(json, false);
}

export function MultiPolygon1ToJSONTyped(value?: MultiPolygon1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MultiPolygon': MultiPolygonToJSON(value['multiPolygon']),
    };
}

