/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPoint } from './MultiPoint';
import {
    MultiPointFromJSON,
    MultiPointFromJSONTyped,
    MultiPointToJSON,
    MultiPointToJSONTyped,
} from './MultiPoint';

/**
 * 
 * @export
 * @interface MultiPoint1
 */
export interface MultiPoint1 {
    /**
     * 
     * @type {MultiPoint}
     * @memberof MultiPoint1
     */
    multiPoint: MultiPoint;
}

/**
 * Check if a given object implements the MultiPoint1 interface.
 */
export function instanceOfMultiPoint1(value: object): value is MultiPoint1 {
    if (!('multiPoint' in value) || value['multiPoint'] === undefined) return false;
    return true;
}

export function MultiPoint1FromJSON(json: any): MultiPoint1 {
    return MultiPoint1FromJSONTyped(json, false);
}

export function MultiPoint1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPoint1 {
    if (json == null) {
        return json;
    }
    return {
        
        'multiPoint': MultiPointFromJSON(json['MultiPoint']),
    };
}

export function MultiPoint1ToJSON(json: any): MultiPoint1 {
    return MultiPoint1ToJSONTyped(json, false);
}

export function MultiPoint1ToJSONTyped(value?: MultiPoint1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MultiPoint': MultiPointToJSON(value['multiPoint']),
    };
}

