/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberParamStatic
 */
export interface NumberParamStatic {
    /**
     * 
     * @type {string}
     * @memberof NumberParamStatic
     */
    type: NumberParamStaticTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof NumberParamStatic
     */
    value: number;
}


/**
 * @export
 */
export const NumberParamStaticTypeEnum = {
    Static: 'static'
} as const;
export type NumberParamStaticTypeEnum = typeof NumberParamStaticTypeEnum[keyof typeof NumberParamStaticTypeEnum];


/**
 * Check if a given object implements the NumberParamStatic interface.
 */
export function instanceOfNumberParamStatic(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function NumberParamStaticFromJSON(json: any): NumberParamStatic {
    return NumberParamStaticFromJSONTyped(json, false);
}

export function NumberParamStaticFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberParamStatic {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function NumberParamStaticToJSON(value?: NumberParamStatic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

