/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Number
 */
export interface Number {
    /**
     * 
     * @type {NumberTypeEnum}
     * @memberof Number
     */
    type: NumberTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Number
     */
    value: number;
}


/**
 * @export
 */
export const NumberTypeEnum = {
    Number: 'number'
} as const;
export type NumberTypeEnum = typeof NumberTypeEnum[keyof typeof NumberTypeEnum];


/**
 * Check if a given object implements the Number interface.
 */
export function instanceOfNumber(value: object): value is Number {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function NumberFromJSON(json: any): Number {
    return NumberFromJSONTyped(json, false);
}

export function NumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): Number {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function NumberToJSON(json: any): Number {
    return NumberToJSONTyped(json, false);
}

export function NumberToJSONTyped(value?: Number | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

