/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OgrSourceDatasetTimeTypeNone
 */
export interface OgrSourceDatasetTimeTypeNone {
    /**
     * 
     * @type {string}
     * @memberof OgrSourceDatasetTimeTypeNone
     */
    type: OgrSourceDatasetTimeTypeNoneTypeEnum;
}


/**
 * @export
 */
export const OgrSourceDatasetTimeTypeNoneTypeEnum = {
    None: 'none',
    Start: 'start',
    StartEnd: 'startEnd',
    StartDuration: 'startDuration'
} as const;
export type OgrSourceDatasetTimeTypeNoneTypeEnum = typeof OgrSourceDatasetTimeTypeNoneTypeEnum[keyof typeof OgrSourceDatasetTimeTypeNoneTypeEnum];


/**
 * Check if a given object implements the OgrSourceDatasetTimeTypeNone interface.
 */
export function instanceOfOgrSourceDatasetTimeTypeNone(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function OgrSourceDatasetTimeTypeNoneFromJSON(json: any): OgrSourceDatasetTimeTypeNone {
    return OgrSourceDatasetTimeTypeNoneFromJSONTyped(json, false);
}

export function OgrSourceDatasetTimeTypeNoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): OgrSourceDatasetTimeTypeNone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function OgrSourceDatasetTimeTypeNoneToJSON(value?: OgrSourceDatasetTimeTypeNone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

