/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Plot } from './Plot';
import {
    instanceOfPlot,
    PlotFromJSON,
    PlotFromJSONTyped,
    PlotToJSON,
} from './Plot';
import type { ProjectUpdateToken } from './ProjectUpdateToken';
import {
    instanceOfProjectUpdateToken,
    ProjectUpdateTokenFromJSON,
    ProjectUpdateTokenFromJSONTyped,
    ProjectUpdateTokenToJSON,
} from './ProjectUpdateToken';

/**
 * @type PlotUpdate
 * 
 * @export
 */
export type PlotUpdate = Plot | ProjectUpdateToken;

export function PlotUpdateFromJSON(json: any): PlotUpdate {
    return PlotUpdateFromJSONTyped(json, false);
}

export function PlotUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotUpdate {
    if (json == null) {
        return json;
    }
    if (instanceOfPlot(json)) {
        return PlotFromJSONTyped(json, true);
    }
    if (instanceOfProjectUpdateToken(json)) {
        return ProjectUpdateTokenFromJSONTyped(json, true);
    }
}

export function PlotUpdateToJSON(value?: PlotUpdate | null): any {
    if (value == null) {
        return value;
    }

    if (typeof value === 'object' && instanceOfPlot(value)) {
        return PlotToJSON(value as Plot);
    }
    if (instanceOfProjectUpdateToken(value)) {
        return ProjectUpdateTokenToJSON(value as ProjectUpdateToken);
    }

    return {};
}

