/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Colorizer } from './Colorizer';
import {
    ColorizerFromJSON,
    ColorizerFromJSONTyped,
    ColorizerToJSON,
} from './Colorizer';

/**
 * 
 * @export
 * @interface RasterColorizerSingleBand
 */
export interface RasterColorizerSingleBand {
    /**
     * 
     * @type {number}
     * @memberof RasterColorizerSingleBand
     */
    band: number;
    /**
     * 
     * @type {Colorizer}
     * @memberof RasterColorizerSingleBand
     */
    bandColorizer: Colorizer;
    /**
     * 
     * @type {string}
     * @memberof RasterColorizerSingleBand
     */
    type: RasterColorizerSingleBandTypeEnum;
}


/**
 * @export
 */
export const RasterColorizerSingleBandTypeEnum = {
    SingleBand: 'singleBand'
} as const;
export type RasterColorizerSingleBandTypeEnum = typeof RasterColorizerSingleBandTypeEnum[keyof typeof RasterColorizerSingleBandTypeEnum];


/**
 * Check if a given object implements the RasterColorizerSingleBand interface.
 */
export function instanceOfRasterColorizerSingleBand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "band" in value;
    isInstance = isInstance && "bandColorizer" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function RasterColorizerSingleBandFromJSON(json: any): RasterColorizerSingleBand {
    return RasterColorizerSingleBandFromJSONTyped(json, false);
}

export function RasterColorizerSingleBandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RasterColorizerSingleBand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'band': json['band'],
        'bandColorizer': ColorizerFromJSON(json['bandColorizer']),
        'type': json['type'],
    };
}

export function RasterColorizerSingleBandToJSON(value?: RasterColorizerSingleBand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'band': value.band,
        'bandColorizer': ColorizerToJSON(value.bandColorizer),
        'type': value.type,
    };
}

