/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameBandsOneOf1
 */
export interface RenameBandsOneOf1 {
    /**
     * 
     * @type {RenameBandsOneOf1TypeEnum}
     * @memberof RenameBandsOneOf1
     */
    type: RenameBandsOneOf1TypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RenameBandsOneOf1
     */
    values: Array<string>;
}


/**
 * @export
 */
export const RenameBandsOneOf1TypeEnum = {
    Suffix: 'suffix'
} as const;
export type RenameBandsOneOf1TypeEnum = typeof RenameBandsOneOf1TypeEnum[keyof typeof RenameBandsOneOf1TypeEnum];


/**
 * Check if a given object implements the RenameBandsOneOf1 interface.
 */
export function instanceOfRenameBandsOneOf1(value: object): value is RenameBandsOneOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function RenameBandsOneOf1FromJSON(json: any): RenameBandsOneOf1 {
    return RenameBandsOneOf1FromJSONTyped(json, false);
}

export function RenameBandsOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameBandsOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'values': json['values'],
    };
}

export function RenameBandsOneOf1ToJSON(json: any): RenameBandsOneOf1 {
    return RenameBandsOneOf1ToJSONTyped(json, false);
}

export function RenameBandsOneOf1ToJSONTyped(value?: RenameBandsOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'values': value['values'],
    };
}

