/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameBandsOneOf2
 */
export interface RenameBandsOneOf2 {
    /**
     * 
     * @type {RenameBandsOneOf2TypeEnum}
     * @memberof RenameBandsOneOf2
     */
    type: RenameBandsOneOf2TypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RenameBandsOneOf2
     */
    values: Array<string>;
}


/**
 * @export
 */
export const RenameBandsOneOf2TypeEnum = {
    Rename: 'rename'
} as const;
export type RenameBandsOneOf2TypeEnum = typeof RenameBandsOneOf2TypeEnum[keyof typeof RenameBandsOneOf2TypeEnum];


/**
 * Check if a given object implements the RenameBandsOneOf2 interface.
 */
export function instanceOfRenameBandsOneOf2(value: object): value is RenameBandsOneOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function RenameBandsOneOf2FromJSON(json: any): RenameBandsOneOf2 {
    return RenameBandsOneOf2FromJSONTyped(json, false);
}

export function RenameBandsOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameBandsOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'values': json['values'],
    };
}

export function RenameBandsOneOf2ToJSON(json: any): RenameBandsOneOf2 {
    return RenameBandsOneOf2ToJSONTyped(json, false);
}

export function RenameBandsOneOf2ToJSONTyped(value?: RenameBandsOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'values': value['values'],
    };
}

