/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameBandsOneOf
 */
export interface RenameBandsOneOf {
    /**
     * 
     * @type {RenameBandsOneOfTypeEnum}
     * @memberof RenameBandsOneOf
     */
    type: RenameBandsOneOfTypeEnum;
}


/**
 * @export
 */
export const RenameBandsOneOfTypeEnum = {
    Default: 'default'
} as const;
export type RenameBandsOneOfTypeEnum = typeof RenameBandsOneOfTypeEnum[keyof typeof RenameBandsOneOfTypeEnum];


/**
 * Check if a given object implements the RenameBandsOneOf interface.
 */
export function instanceOfRenameBandsOneOf(value: object): value is RenameBandsOneOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RenameBandsOneOfFromJSON(json: any): RenameBandsOneOf {
    return RenameBandsOneOfFromJSONTyped(json, false);
}

export function RenameBandsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameBandsOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function RenameBandsOneOfToJSON(json: any): RenameBandsOneOf {
    return RenameBandsOneOfToJSONTyped(json, false);
}

export function RenameBandsOneOfToJSONTyped(value?: RenameBandsOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

