/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceLayerCollection
 */
export interface ResourceLayerCollection {
    /**
     * 
     * @type {string}
     * @memberof ResourceLayerCollection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceLayerCollection
     */
    type: ResourceLayerCollectionTypeEnum;
}


/**
 * @export
 */
export const ResourceLayerCollectionTypeEnum = {
    LayerCollection: 'layerCollection'
} as const;
export type ResourceLayerCollectionTypeEnum = typeof ResourceLayerCollectionTypeEnum[keyof typeof ResourceLayerCollectionTypeEnum];


/**
 * Check if a given object implements the ResourceLayerCollection interface.
 */
export function instanceOfResourceLayerCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ResourceLayerCollectionFromJSON(json: any): ResourceLayerCollection {
    return ResourceLayerCollectionFromJSONTyped(json, false);
}

export function ResourceLayerCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLayerCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ResourceLayerCollectionToJSON(value?: ResourceLayerCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

