/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceLayer
 */
export interface ResourceLayer {
    /**
     * 
     * @type {string}
     * @memberof ResourceLayer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceLayer
     */
    type: ResourceLayerTypeEnum;
}


/**
 * @export
 */
export const ResourceLayerTypeEnum = {
    Layer: 'layer',
    LayerCollection: 'layerCollection',
    Project: 'project',
    Dataset: 'dataset'
} as const;
export type ResourceLayerTypeEnum = typeof ResourceLayerTypeEnum[keyof typeof ResourceLayerTypeEnum];


/**
 * Check if a given object implements the ResourceLayer interface.
 */
export function instanceOfResourceLayer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ResourceLayerFromJSON(json: any): ResourceLayer {
    return ResourceLayerFromJSONTyped(json, false);
}

export function ResourceLayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLayer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ResourceLayerToJSON(value?: ResourceLayer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

