/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceIdModelId
 */
export interface ResourceIdModelId {
    /**
     * 
     * @type {string}
     * @memberof ResourceIdModelId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceIdModelId
     */
    type: ResourceIdModelIdTypeEnum;
}


/**
 * @export
 */
export const ResourceIdModelIdTypeEnum = {
    ModelId: 'ModelId'
} as const;
export type ResourceIdModelIdTypeEnum = typeof ResourceIdModelIdTypeEnum[keyof typeof ResourceIdModelIdTypeEnum];


/**
 * Check if a given object implements the ResourceIdModelId interface.
 */
export function instanceOfResourceIdModelId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ResourceIdModelIdFromJSON(json: any): ResourceIdModelId {
    return ResourceIdModelIdFromJSONTyped(json, false);
}

export function ResourceIdModelIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceIdModelId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ResourceIdModelIdToJSON(value?: ResourceIdModelId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

