/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ResourceIdDatasetId,
    instanceOfResourceIdDatasetId,
    ResourceIdDatasetIdFromJSON,
    ResourceIdDatasetIdFromJSONTyped,
    ResourceIdDatasetIdToJSON,
} from './ResourceIdDatasetId';
import {
    ResourceIdLayer,
    instanceOfResourceIdLayer,
    ResourceIdLayerFromJSON,
    ResourceIdLayerFromJSONTyped,
    ResourceIdLayerToJSON,
} from './ResourceIdLayer';
import {
    ResourceIdLayerCollection,
    instanceOfResourceIdLayerCollection,
    ResourceIdLayerCollectionFromJSON,
    ResourceIdLayerCollectionFromJSONTyped,
    ResourceIdLayerCollectionToJSON,
} from './ResourceIdLayerCollection';
import {
    ResourceIdProject,
    instanceOfResourceIdProject,
    ResourceIdProjectFromJSON,
    ResourceIdProjectFromJSONTyped,
    ResourceIdProjectToJSON,
} from './ResourceIdProject';

/**
 * @type ResourceId
 * 
 * @export
 */
export type ResourceId = { type: 'DatasetId' } & ResourceIdDatasetId | { type: 'Layer' } & ResourceIdLayer | { type: 'LayerCollection' } & ResourceIdLayerCollection | { type: 'Project' } & ResourceIdProject;

export function ResourceIdFromJSON(json: any): ResourceId {
    return ResourceIdFromJSONTyped(json, false);
}

export function ResourceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'DatasetId':
            return {...ResourceIdDatasetIdFromJSONTyped(json, true), type: 'DatasetId'};
        case 'Layer':
            return {...ResourceIdLayerFromJSONTyped(json, true), type: 'Layer'};
        case 'LayerCollection':
            return {...ResourceIdLayerCollectionFromJSONTyped(json, true), type: 'LayerCollection'};
        case 'Project':
            return {...ResourceIdProjectFromJSONTyped(json, true), type: 'Project'};
        default:
            throw new Error(`No variant of ResourceId exists with 'type=${json['type']}'`);
    }
}

export function ResourceIdToJSON(value?: ResourceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'DatasetId':
            return ResourceIdDatasetIdToJSON(value);
        case 'Layer':
            return ResourceIdLayerToJSON(value);
        case 'LayerCollection':
            return ResourceIdLayerCollectionToJSON(value);
        case 'Project':
            return ResourceIdProjectToJSON(value);
        default:
            throw new Error(`No variant of ResourceId exists with 'type=${value['type']}'`);
    }

}

