/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceIdLayer
 */
export interface ResourceIdLayer {
    /**
     * 
     * @type {string}
     * @memberof ResourceIdLayer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceIdLayer
     */
    type: ResourceIdLayerTypeEnum;
}


/**
 * @export
 */
export const ResourceIdLayerTypeEnum = {
    Layer: 'Layer'
} as const;
export type ResourceIdLayerTypeEnum = typeof ResourceIdLayerTypeEnum[keyof typeof ResourceIdLayerTypeEnum];


/**
 * Check if a given object implements the ResourceIdLayer interface.
 */
export function instanceOfResourceIdLayer(value: object): value is ResourceIdLayer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResourceIdLayerFromJSON(json: any): ResourceIdLayer {
    return ResourceIdLayerFromJSONTyped(json, false);
}

export function ResourceIdLayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceIdLayer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ResourceIdLayerToJSON(value?: ResourceIdLayer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

