/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SquareRootChoiceRule
 */
export interface SquareRootChoiceRule {
    /**
     * 
     * @type {number}
     * @memberof SquareRootChoiceRule
     */
    maxNumberOfBuckets?: number;
    /**
     * 
     * @type {SquareRootChoiceRuleTypeEnum}
     * @memberof SquareRootChoiceRule
     */
    type: SquareRootChoiceRuleTypeEnum;
}


/**
 * @export
 */
export const SquareRootChoiceRuleTypeEnum = {
    SquareRootChoiceRule: 'squareRootChoiceRule'
} as const;
export type SquareRootChoiceRuleTypeEnum = typeof SquareRootChoiceRuleTypeEnum[keyof typeof SquareRootChoiceRuleTypeEnum];


/**
 * Check if a given object implements the SquareRootChoiceRule interface.
 */
export function instanceOfSquareRootChoiceRule(value: object): value is SquareRootChoiceRule {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SquareRootChoiceRuleFromJSON(json: any): SquareRootChoiceRule {
    return SquareRootChoiceRuleFromJSONTyped(json, false);
}

export function SquareRootChoiceRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SquareRootChoiceRule {
    if (json == null) {
        return json;
    }
    return {
        
        'maxNumberOfBuckets': json['maxNumberOfBuckets'] == null ? undefined : json['maxNumberOfBuckets'],
        'type': json['type'],
    };
}

export function SquareRootChoiceRuleToJSON(json: any): SquareRootChoiceRule {
    return SquareRootChoiceRuleToJSONTyped(json, false);
}

export function SquareRootChoiceRuleToJSONTyped(value?: SquareRootChoiceRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxNumberOfBuckets': value['maxNumberOfBuckets'],
        'type': value['type'],
    };
}

