/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StacZone
 */
export interface StacZone {
    /**
     * 
     * @type {number}
     * @memberof StacZone
     */
    epsg: number;
    /**
     * 
     * @type {string}
     * @memberof StacZone
     */
    name: string;
}

/**
 * Check if a given object implements the StacZone interface.
 */
export function instanceOfStacZone(value: object): value is StacZone {
    if (!('epsg' in value) || value['epsg'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StacZoneFromJSON(json: any): StacZone {
    return StacZoneFromJSONTyped(json, false);
}

export function StacZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacZone {
    if (json == null) {
        return json;
    }
    return {
        
        'epsg': json['epsg'],
        'name': json['name'],
    };
}

export function StacZoneToJSON(json: any): StacZone {
    return StacZoneToJSONTyped(json, false);
}

export function StacZoneToJSONTyped(value?: StacZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'epsg': value['epsg'],
        'name': value['name'],
    };
}

