/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaticNumberParam
 */
export interface StaticNumberParam {
    /**
     * 
     * @type {string}
     * @memberof StaticNumberParam
     */
    type: StaticNumberParamTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof StaticNumberParam
     */
    value: number;
}


/**
 * @export
 */
export const StaticNumberParamTypeEnum = {
    Static: 'static'
} as const;
export type StaticNumberParamTypeEnum = typeof StaticNumberParamTypeEnum[keyof typeof StaticNumberParamTypeEnum];


/**
 * Check if a given object implements the StaticNumberParam interface.
 */
export function instanceOfStaticNumberParam(value: object): value is StaticNumberParam {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function StaticNumberParamFromJSON(json: any): StaticNumberParam {
    return StaticNumberParamFromJSONTyped(json, false);
}

export function StaticNumberParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaticNumberParam {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function StaticNumberParamToJSON(json: any): StaticNumberParam {
    return StaticNumberParamToJSONTyped(json, false);
}

export function StaticNumberParamToJSONTyped(value?: StaticNumberParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

