/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineSymbology,
    instanceOfLineSymbology,
    LineSymbologyFromJSON,
    LineSymbologyFromJSONTyped,
    LineSymbologyToJSON,
} from './LineSymbology';
import {
    PointSymbology,
    instanceOfPointSymbology,
    PointSymbologyFromJSON,
    PointSymbologyFromJSONTyped,
    PointSymbologyToJSON,
} from './PointSymbology';
import {
    PolygonSymbology,
    instanceOfPolygonSymbology,
    PolygonSymbologyFromJSON,
    PolygonSymbologyFromJSONTyped,
    PolygonSymbologyToJSON,
} from './PolygonSymbology';
import {
    RasterSymbology,
    instanceOfRasterSymbology,
    RasterSymbologyFromJSON,
    RasterSymbologyFromJSONTyped,
    RasterSymbologyToJSON,
} from './RasterSymbology';

/**
 * @type Symbology
 * 
 * @export
 */
export type Symbology = { type: 'line' } & LineSymbology | { type: 'point' } & PointSymbology | { type: 'polygon' } & PolygonSymbology | { type: 'raster' } & RasterSymbology;

export function SymbologyFromJSON(json: any): Symbology {
    return SymbologyFromJSONTyped(json, false);
}

export function SymbologyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Symbology {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'line':
            return {...LineSymbologyFromJSONTyped(json, true), type: 'line'};
        case 'point':
            return {...PointSymbologyFromJSONTyped(json, true), type: 'point'};
        case 'polygon':
            return {...PolygonSymbologyFromJSONTyped(json, true), type: 'polygon'};
        case 'raster':
            return {...RasterSymbologyFromJSONTyped(json, true), type: 'raster'};
        default:
            throw new Error(`No variant of Symbology exists with 'type=${json['type']}'`);
    }
}

export function SymbologyToJSON(value?: Symbology | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'line':
            return LineSymbologyToJSON(value);
        case 'point':
            return PointSymbologyToJSON(value);
        case 'polygon':
            return PolygonSymbologyToJSON(value);
        case 'raster':
            return RasterSymbologyToJSON(value);
        default:
            throw new Error(`No variant of Symbology exists with 'type=${value['type']}'`);
    }

}

