/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeStep } from './TimeStep';
import {
    TimeStepFromJSON,
    TimeStepFromJSONTyped,
    TimeStepToJSON,
    TimeStepToJSONTyped,
} from './TimeStep';
import type { RegularTimeDimension } from './RegularTimeDimension';
import {
    RegularTimeDimensionFromJSON,
    RegularTimeDimensionFromJSONTyped,
    RegularTimeDimensionToJSON,
    RegularTimeDimensionToJSONTyped,
} from './RegularTimeDimension';

/**
 * 
 * @export
 * @interface TimeDimensionOneOf
 */
export interface TimeDimensionOneOf extends RegularTimeDimension {
    /**
     * 
     * @type {string}
     * @memberof TimeDimensionOneOf
     */
    type: TimeDimensionOneOfTypeEnum;
}


/**
 * @export
 */
export const TimeDimensionOneOfTypeEnum = {
    Regular: 'regular'
} as const;
export type TimeDimensionOneOfTypeEnum = typeof TimeDimensionOneOfTypeEnum[keyof typeof TimeDimensionOneOfTypeEnum];


/**
 * Check if a given object implements the TimeDimensionOneOf interface.
 */
export function instanceOfTimeDimensionOneOf(value: object): value is TimeDimensionOneOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TimeDimensionOneOfFromJSON(json: any): TimeDimensionOneOf {
    return TimeDimensionOneOfFromJSONTyped(json, false);
}

export function TimeDimensionOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDimensionOneOf {
    if (json == null) {
        return json;
    }
    return {
        ...RegularTimeDimensionFromJSONTyped(json, true),
        'type': json['type'],
    };
}

export function TimeDimensionOneOfToJSON(json: any): TimeDimensionOneOf {
    return TimeDimensionOneOfToJSONTyped(json, false);
}

export function TimeDimensionOneOfToJSONTyped(value?: TimeDimensionOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...RegularTimeDimensionToJSONTyped(value, true),
        'type': value['type'],
    };
}

