/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BoundingBox2D } from './BoundingBox2D';
import {
    BoundingBox2DFromJSON,
    BoundingBox2DFromJSONTyped,
    BoundingBox2DToJSON,
} from './BoundingBox2D';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';
import type { VectorColumnInfo } from './VectorColumnInfo';
import {
    VectorColumnInfoFromJSON,
    VectorColumnInfoFromJSONTyped,
    VectorColumnInfoToJSON,
} from './VectorColumnInfo';
import type { VectorDataType } from './VectorDataType';
import {
    VectorDataTypeFromJSON,
    VectorDataTypeFromJSONTyped,
    VectorDataTypeToJSON,
} from './VectorDataType';

/**
 * 
 * @export
 * @interface TypedResultDescriptorVector
 */
export interface TypedResultDescriptorVector {
    /**
     * 
     * @type {BoundingBox2D}
     * @memberof TypedResultDescriptorVector
     */
    bbox?: BoundingBox2D;
    /**
     * 
     * @type {{ [key: string]: VectorColumnInfo; }}
     * @memberof TypedResultDescriptorVector
     */
    columns: { [key: string]: VectorColumnInfo; };
    /**
     * 
     * @type {VectorDataType}
     * @memberof TypedResultDescriptorVector
     */
    dataType: VectorDataType;
    /**
     * 
     * @type {string}
     * @memberof TypedResultDescriptorVector
     */
    spatialReference: string;
    /**
     * 
     * @type {TimeInterval}
     * @memberof TypedResultDescriptorVector
     */
    time?: TimeInterval;
    /**
     * 
     * @type {string}
     * @memberof TypedResultDescriptorVector
     */
    type: TypedResultDescriptorVectorTypeEnum;
}


/**
 * @export
 */
export const TypedResultDescriptorVectorTypeEnum = {
    Vector: 'vector'
} as const;
export type TypedResultDescriptorVectorTypeEnum = typeof TypedResultDescriptorVectorTypeEnum[keyof typeof TypedResultDescriptorVectorTypeEnum];


/**
 * Check if a given object implements the TypedResultDescriptorVector interface.
 */
export function instanceOfTypedResultDescriptorVector(value: object): boolean {
    if (!('columns' in value)) return false;
    if (!('dataType' in value)) return false;
    if (!('spatialReference' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function TypedResultDescriptorVectorFromJSON(json: any): TypedResultDescriptorVector {
    return TypedResultDescriptorVectorFromJSONTyped(json, false);
}

export function TypedResultDescriptorVectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedResultDescriptorVector {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BoundingBox2DFromJSON(json['bbox']),
        'columns': (mapValues(json['columns'], VectorColumnInfoFromJSON)),
        'dataType': VectorDataTypeFromJSON(json['dataType']),
        'spatialReference': json['spatialReference'],
        'time': json['time'] == null ? undefined : TimeIntervalFromJSON(json['time']),
        'type': json['type'],
    };
}

export function TypedResultDescriptorVectorToJSON(value?: TypedResultDescriptorVector | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bbox': BoundingBox2DToJSON(value['bbox']),
        'columns': (mapValues(value['columns'], VectorColumnInfoToJSON)),
        'dataType': VectorDataTypeToJSON(value['dataType']),
        'spatialReference': value['spatialReference'],
        'time': TimeIntervalToJSON(value['time']),
        'type': value['type'],
    };
}

