/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorOperator } from './VectorOperator';
import {
    VectorOperatorFromJSON,
    VectorOperatorFromJSONTyped,
    VectorOperatorToJSON,
    VectorOperatorToJSONTyped,
} from './VectorOperator';

/**
 * 
 * @export
 * @interface TypedOperatorOneOf
 */
export interface TypedOperatorOneOf {
    /**
     * 
     * @type {VectorOperator}
     * @memberof TypedOperatorOneOf
     */
    operator: VectorOperator;
    /**
     * 
     * @type {TypedOperatorOneOfTypeEnum}
     * @memberof TypedOperatorOneOf
     */
    type: TypedOperatorOneOfTypeEnum;
}


/**
 * @export
 */
export const TypedOperatorOneOfTypeEnum = {
    Vector: 'Vector'
} as const;
export type TypedOperatorOneOfTypeEnum = typeof TypedOperatorOneOfTypeEnum[keyof typeof TypedOperatorOneOfTypeEnum];


/**
 * Check if a given object implements the TypedOperatorOneOf interface.
 */
export function instanceOfTypedOperatorOneOf(value: object): value is TypedOperatorOneOf {
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedOperatorOneOfFromJSON(json: any): TypedOperatorOneOf {
    return TypedOperatorOneOfFromJSONTyped(json, false);
}

export function TypedOperatorOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedOperatorOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': VectorOperatorFromJSON(json['operator']),
        'type': json['type'],
    };
}

export function TypedOperatorOneOfToJSON(json: any): TypedOperatorOneOf {
    return TypedOperatorOneOfToJSONTyped(json, false);
}

export function TypedOperatorOneOfToJSONTyped(value?: TypedOperatorOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': VectorOperatorToJSON(value['operator']),
        'type': value['type'],
    };
}

