/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpatialResolution } from './SpatialResolution';
import {
    SpatialResolutionFromJSON,
    SpatialResolutionFromJSONTyped,
    SpatialResolutionToJSON,
} from './SpatialResolution';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';
import type { RasterBandDescriptor } from './RasterBandDescriptor';
import {
    RasterBandDescriptorFromJSON,
    RasterBandDescriptorFromJSONTyped,
    RasterBandDescriptorToJSON,
} from './RasterBandDescriptor';
import type { RasterDataType } from './RasterDataType';
import {
    RasterDataTypeFromJSON,
    RasterDataTypeFromJSONTyped,
    RasterDataTypeToJSON,
} from './RasterDataType';
import type { SpatialPartition2D } from './SpatialPartition2D';
import {
    SpatialPartition2DFromJSON,
    SpatialPartition2DFromJSONTyped,
    SpatialPartition2DToJSON,
} from './SpatialPartition2D';

/**
 * A `ResultDescriptor` for raster queries
 * @export
 * @interface TypedResultDescriptorRaster
 */
export interface TypedResultDescriptorRaster {
    /**
     * 
     * @type {Array<RasterBandDescriptor>}
     * @memberof TypedResultDescriptorRaster
     */
    bands: Array<RasterBandDescriptor>;
    /**
     * 
     * @type {SpatialPartition2D}
     * @memberof TypedResultDescriptorRaster
     */
    bbox?: SpatialPartition2D;
    /**
     * 
     * @type {RasterDataType}
     * @memberof TypedResultDescriptorRaster
     */
    dataType: RasterDataType;
    /**
     * 
     * @type {SpatialResolution}
     * @memberof TypedResultDescriptorRaster
     */
    resolution?: SpatialResolution;
    /**
     * 
     * @type {string}
     * @memberof TypedResultDescriptorRaster
     */
    spatialReference: string;
    /**
     * 
     * @type {TimeInterval}
     * @memberof TypedResultDescriptorRaster
     */
    time?: TimeInterval;
    /**
     * 
     * @type {string}
     * @memberof TypedResultDescriptorRaster
     */
    type: TypedResultDescriptorRasterTypeEnum;
}


/**
 * @export
 */
export const TypedResultDescriptorRasterTypeEnum = {
    Raster: 'raster'
} as const;
export type TypedResultDescriptorRasterTypeEnum = typeof TypedResultDescriptorRasterTypeEnum[keyof typeof TypedResultDescriptorRasterTypeEnum];


/**
 * Check if a given object implements the TypedResultDescriptorRaster interface.
 */
export function instanceOfTypedResultDescriptorRaster(value: object): value is TypedResultDescriptorRaster {
    if (!('bands' in value) || value['bands'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('spatialReference' in value) || value['spatialReference'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedResultDescriptorRasterFromJSON(json: any): TypedResultDescriptorRaster {
    return TypedResultDescriptorRasterFromJSONTyped(json, false);
}

export function TypedResultDescriptorRasterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedResultDescriptorRaster {
    if (json == null) {
        return json;
    }
    return {
        
        'bands': ((json['bands'] as Array<any>).map(RasterBandDescriptorFromJSON)),
        'bbox': json['bbox'] == null ? undefined : SpatialPartition2DFromJSON(json['bbox']),
        'dataType': RasterDataTypeFromJSON(json['dataType']),
        'resolution': json['resolution'] == null ? undefined : SpatialResolutionFromJSON(json['resolution']),
        'spatialReference': json['spatialReference'],
        'time': json['time'] == null ? undefined : TimeIntervalFromJSON(json['time']),
        'type': json['type'],
    };
}

export function TypedResultDescriptorRasterToJSON(value?: TypedResultDescriptorRaster | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bands': ((value['bands'] as Array<any>).map(RasterBandDescriptorToJSON)),
        'bbox': SpatialPartition2DToJSON(value['bbox']),
        'dataType': RasterDataTypeToJSON(value['dataType']),
        'resolution': SpatialResolutionToJSON(value['resolution']),
        'spatialReference': value['spatialReference'],
        'time': TimeIntervalToJSON(value['time']),
        'type': value['type'],
    };
}

