/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MultiLineString1 } from './MultiLineString1';
import {
    instanceOfMultiLineString1,
    MultiLineString1FromJSON,
    MultiLineString1FromJSONTyped,
    MultiLineString1ToJSON,
} from './MultiLineString1';
import type { MultiPoint1 } from './MultiPoint1';
import {
    instanceOfMultiPoint1,
    MultiPoint1FromJSON,
    MultiPoint1FromJSONTyped,
    MultiPoint1ToJSON,
} from './MultiPoint1';
import type { MultiPolygon1 } from './MultiPolygon1';
import {
    instanceOfMultiPolygon1,
    MultiPolygon1FromJSON,
    MultiPolygon1FromJSONTyped,
    MultiPolygon1ToJSON,
} from './MultiPolygon1';
import type { NoGeometry1 } from './NoGeometry1';
import {
    instanceOfNoGeometry1,
    NoGeometry1FromJSON,
    NoGeometry1FromJSONTyped,
    NoGeometry1ToJSON,
} from './NoGeometry1';

/**
 * @type TypedGeometry
 * 
 * @export
 */
export type TypedGeometry = MultiLineString1 | MultiPoint1 | MultiPolygon1 | NoGeometry1;

export function TypedGeometryFromJSON(json: any): TypedGeometry {
    return TypedGeometryFromJSONTyped(json, false);
}

export function TypedGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedGeometry {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfMultiLineString1(json)) {
        return MultiLineString1FromJSONTyped(json, true);
    }
    if (instanceOfMultiPoint1(json)) {
        return MultiPoint1FromJSONTyped(json, true);
    }
    if (instanceOfMultiPolygon1(json)) {
        return MultiPolygon1FromJSONTyped(json, true);
    }
    if (instanceOfNoGeometry1(json)) {
        return NoGeometry1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function TypedGeometryToJSON(json: any): any {
    return TypedGeometryToJSONTyped(json, false);
}

export function TypedGeometryToJSONTyped(value?: TypedGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfMultiLineString1(value)) {
        return MultiLineString1ToJSON(value as MultiLineString1);
    }
    if (instanceOfMultiPoint1(value)) {
        return MultiPoint1ToJSON(value as MultiPoint1);
    }
    if (instanceOfMultiPolygon1(value)) {
        return MultiPolygon1ToJSON(value as MultiPolygon1);
    }
    if (instanceOfNoGeometry1(value)) {
        return NoGeometry1ToJSON(value as NoGeometry1);
    }
    return {};
}

