/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
    TimeIntervalToJSONTyped,
} from './TimeInterval';
import type { BoundingBox2D } from './BoundingBox2D';
import {
    BoundingBox2DFromJSON,
    BoundingBox2DFromJSONTyped,
    BoundingBox2DToJSON,
    BoundingBox2DToJSONTyped,
} from './BoundingBox2D';

/**
 * A `ResultDescriptor` for plot queries
 * @export
 * @interface TypedPlotResultDescriptor
 */
export interface TypedPlotResultDescriptor {
    /**
     * 
     * @type {BoundingBox2D}
     * @memberof TypedPlotResultDescriptor
     */
    bbox?: BoundingBox2D | null;
    /**
     * 
     * @type {string}
     * @memberof TypedPlotResultDescriptor
     */
    spatialReference: string;
    /**
     * 
     * @type {TimeInterval}
     * @memberof TypedPlotResultDescriptor
     */
    time?: TimeInterval | null;
    /**
     * 
     * @type {string}
     * @memberof TypedPlotResultDescriptor
     */
    type: TypedPlotResultDescriptorTypeEnum;
}


/**
 * @export
 */
export const TypedPlotResultDescriptorTypeEnum = {
    Plot: 'plot'
} as const;
export type TypedPlotResultDescriptorTypeEnum = typeof TypedPlotResultDescriptorTypeEnum[keyof typeof TypedPlotResultDescriptorTypeEnum];


/**
 * Check if a given object implements the TypedPlotResultDescriptor interface.
 */
export function instanceOfTypedPlotResultDescriptor(value: object): value is TypedPlotResultDescriptor {
    if (!('spatialReference' in value) || value['spatialReference'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedPlotResultDescriptorFromJSON(json: any): TypedPlotResultDescriptor {
    return TypedPlotResultDescriptorFromJSONTyped(json, false);
}

export function TypedPlotResultDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedPlotResultDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BoundingBox2DFromJSON(json['bbox']),
        'spatialReference': json['spatialReference'],
        'time': json['time'] == null ? undefined : TimeIntervalFromJSON(json['time']),
        'type': json['type'],
    };
}

export function TypedPlotResultDescriptorToJSON(json: any): TypedPlotResultDescriptor {
    return TypedPlotResultDescriptorToJSONTyped(json, false);
}

export function TypedPlotResultDescriptorToJSONTyped(value?: TypedPlotResultDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BoundingBox2DToJSON(value['bbox']),
        'spatialReference': value['spatialReference'],
        'time': TimeIntervalToJSON(value['time']),
        'type': value['type'],
    };
}

