/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RasterOperator } from './RasterOperator';
import {
    RasterOperatorFromJSON,
    RasterOperatorFromJSONTyped,
    RasterOperatorToJSON,
    RasterOperatorToJSONTyped,
} from './RasterOperator';

/**
 * 
 * @export
 * @interface TypedOperatorOneOf1
 */
export interface TypedOperatorOneOf1 {
    /**
     * 
     * @type {RasterOperator}
     * @memberof TypedOperatorOneOf1
     */
    operator: RasterOperator;
    /**
     * 
     * @type {TypedOperatorOneOf1TypeEnum}
     * @memberof TypedOperatorOneOf1
     */
    type: TypedOperatorOneOf1TypeEnum;
}


/**
 * @export
 */
export const TypedOperatorOneOf1TypeEnum = {
    Raster: 'Raster'
} as const;
export type TypedOperatorOneOf1TypeEnum = typeof TypedOperatorOneOf1TypeEnum[keyof typeof TypedOperatorOneOf1TypeEnum];


/**
 * Check if a given object implements the TypedOperatorOneOf1 interface.
 */
export function instanceOfTypedOperatorOneOf1(value: object): value is TypedOperatorOneOf1 {
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedOperatorOneOf1FromJSON(json: any): TypedOperatorOneOf1 {
    return TypedOperatorOneOf1FromJSONTyped(json, false);
}

export function TypedOperatorOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedOperatorOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': RasterOperatorFromJSON(json['operator']),
        'type': json['type'],
    };
}

export function TypedOperatorOneOf1ToJSON(json: any): TypedOperatorOneOf1 {
    return TypedOperatorOneOf1ToJSONTyped(json, false);
}

export function TypedOperatorOneOf1ToJSONTyped(value?: TypedOperatorOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': RasterOperatorToJSON(value['operator']),
        'type': value['type'],
    };
}

