/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypedOperatorOperator
 */
export interface TypedOperatorOperator {
    /**
     * 
     * @type {object}
     * @memberof TypedOperatorOperator
     */
    params?: object;
    /**
     * 
     * @type {object}
     * @memberof TypedOperatorOperator
     */
    sources?: object;
    /**
     * 
     * @type {string}
     * @memberof TypedOperatorOperator
     */
    type: string;
}

/**
 * Check if a given object implements the TypedOperatorOperator interface.
 */
export function instanceOfTypedOperatorOperator(value: object): value is TypedOperatorOperator {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedOperatorOperatorFromJSON(json: any): TypedOperatorOperator {
    return TypedOperatorOperatorFromJSONTyped(json, false);
}

export function TypedOperatorOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedOperatorOperator {
    if (json == null) {
        return json;
    }
    return {
        
        'params': json['params'] == null ? undefined : json['params'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'type': json['type'],
    };
}

export function TypedOperatorOperatorToJSON(json: any): TypedOperatorOperator {
    return TypedOperatorOperatorToJSONTyped(json, false);
}

export function TypedOperatorOperatorToJSONTyped(value?: TypedOperatorOperator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'params': value['params'],
        'sources': value['sources'],
        'type': value['type'],
    };
}

