/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlotOperator } from './PlotOperator';
import {
    PlotOperatorFromJSON,
    PlotOperatorFromJSONTyped,
    PlotOperatorToJSON,
    PlotOperatorToJSONTyped,
} from './PlotOperator';

/**
 * 
 * @export
 * @interface TypedOperatorOneOf2
 */
export interface TypedOperatorOneOf2 {
    /**
     * 
     * @type {PlotOperator}
     * @memberof TypedOperatorOneOf2
     */
    operator: PlotOperator;
    /**
     * 
     * @type {TypedOperatorOneOf2TypeEnum}
     * @memberof TypedOperatorOneOf2
     */
    type: TypedOperatorOneOf2TypeEnum;
}


/**
 * @export
 */
export const TypedOperatorOneOf2TypeEnum = {
    Plot: 'Plot'
} as const;
export type TypedOperatorOneOf2TypeEnum = typeof TypedOperatorOneOf2TypeEnum[keyof typeof TypedOperatorOneOf2TypeEnum];


/**
 * Check if a given object implements the TypedOperatorOneOf2 interface.
 */
export function instanceOfTypedOperatorOneOf2(value: object): value is TypedOperatorOneOf2 {
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TypedOperatorOneOf2FromJSON(json: any): TypedOperatorOneOf2 {
    return TypedOperatorOneOf2FromJSONTyped(json, false);
}

export function TypedOperatorOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedOperatorOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': PlotOperatorFromJSON(json['operator']),
        'type': json['type'],
    };
}

export function TypedOperatorOneOf2ToJSON(json: any): TypedOperatorOneOf2 {
    return TypedOperatorOneOf2ToJSONTyped(json, false);
}

export function TypedOperatorOneOf2ToJSONTyped(value?: TypedOperatorOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': PlotOperatorToJSON(value['operator']),
        'type': value['type'],
    };
}

