/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
    TimeIntervalToJSONTyped,
} from './TimeInterval';
import type { GdalDatasetParameters } from './GdalDatasetParameters';
import {
    GdalDatasetParametersFromJSON,
    GdalDatasetParametersFromJSONTyped,
    GdalDatasetParametersToJSON,
    GdalDatasetParametersToJSONTyped,
} from './GdalDatasetParameters';
import type { SpatialPartition2D } from './SpatialPartition2D';
import {
    SpatialPartition2DFromJSON,
    SpatialPartition2DFromJSONTyped,
    SpatialPartition2DToJSON,
    SpatialPartition2DToJSONTyped,
} from './SpatialPartition2D';

/**
 * 
 * @export
 * @interface UpdateDatasetTile
 */
export interface UpdateDatasetTile {
    /**
     * 
     * @type {number}
     * @memberof UpdateDatasetTile
     */
    band: number;
    /**
     * 
     * @type {GdalDatasetParameters}
     * @memberof UpdateDatasetTile
     */
    params: GdalDatasetParameters;
    /**
     * 
     * @type {SpatialPartition2D}
     * @memberof UpdateDatasetTile
     */
    spatialPartition: SpatialPartition2D;
    /**
     * 
     * @type {TimeInterval}
     * @memberof UpdateDatasetTile
     */
    time: TimeInterval;
    /**
     * 
     * @type {number}
     * @memberof UpdateDatasetTile
     */
    zIndex: number;
}

/**
 * Check if a given object implements the UpdateDatasetTile interface.
 */
export function instanceOfUpdateDatasetTile(value: object): value is UpdateDatasetTile {
    if (!('band' in value) || value['band'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('spatialPartition' in value) || value['spatialPartition'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('zIndex' in value) || value['zIndex'] === undefined) return false;
    return true;
}

export function UpdateDatasetTileFromJSON(json: any): UpdateDatasetTile {
    return UpdateDatasetTileFromJSONTyped(json, false);
}

export function UpdateDatasetTileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDatasetTile {
    if (json == null) {
        return json;
    }
    return {
        
        'band': json['band'],
        'params': GdalDatasetParametersFromJSON(json['params']),
        'spatialPartition': SpatialPartition2DFromJSON(json['spatial_partition']),
        'time': TimeIntervalFromJSON(json['time']),
        'zIndex': json['z_index'],
    };
}

export function UpdateDatasetTileToJSON(json: any): UpdateDatasetTile {
    return UpdateDatasetTileToJSONTyped(json, false);
}

export function UpdateDatasetTileToJSONTyped(value?: UpdateDatasetTile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'band': value['band'],
        'params': GdalDatasetParametersToJSON(value['params']),
        'spatial_partition': SpatialPartition2DToJSON(value['spatialPartition']),
        'time': TimeIntervalToJSON(value['time']),
        'z_index': value['zIndex'],
    };
}

