/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegistration
 */
export interface UserRegistration {
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    realName: string;
}

/**
 * Check if a given object implements the UserRegistration interface.
 */
export function instanceOfUserRegistration(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    if (!('realName' in value)) return false;
    return true;
}

export function UserRegistrationFromJSON(json: any): UserRegistration {
    return UserRegistrationFromJSONTyped(json, false);
}

export function UserRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'realName': json['realName'],
    };
}

export function UserRegistrationToJSON(value?: UserRegistration | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'realName': value['realName'],
    };
}

