/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValuesValues } from './ValuesValues';
import {
    ValuesValuesFromJSON,
    ValuesValuesFromJSONTyped,
    ValuesValuesToJSON,
    ValuesValuesToJSONTyped,
} from './ValuesValues';

/**
 * 
 * @export
 * @interface Values
 */
export interface Values {
    /**
     * 
     * @type {ValuesValues}
     * @memberof Values
     */
    values: ValuesValues;
}

/**
 * Check if a given object implements the Values interface.
 */
export function instanceOfValues(value: object): value is Values {
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function ValuesFromJSON(json: any): Values {
    return ValuesFromJSONTyped(json, false);
}

export function ValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Values {
    if (json == null) {
        return json;
    }
    return {
        
        'values': ValuesValuesFromJSON(json['values']),
    };
}

export function ValuesToJSON(json: any): Values {
    return ValuesToJSONTyped(json, false);
}

export function ValuesToJSONTyped(value?: Values | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': ValuesValuesToJSON(value['values']),
    };
}

