/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypedOperatorOperator } from './TypedOperatorOperator';
import {
    TypedOperatorOperatorFromJSON,
    TypedOperatorOperatorFromJSONTyped,
    TypedOperatorOperatorToJSON,
} from './TypedOperatorOperator';

/**
 * 
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     * 
     * @type {TypedOperatorOperator}
     * @memberof Workflow
     */
    operator: TypedOperatorOperator;
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    type: WorkflowTypeEnum;
}


/**
 * @export
 */
export const WorkflowTypeEnum = {
    Vector: 'Vector',
    Raster: 'Raster',
    Plot: 'Plot'
} as const;
export type WorkflowTypeEnum = typeof WorkflowTypeEnum[keyof typeof WorkflowTypeEnum];


/**
 * Check if a given object implements the Workflow interface.
 */
export function instanceOfWorkflow(value: object): boolean {
    if (!('operator' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function WorkflowFromJSON(json: any): Workflow {
    return WorkflowFromJSONTyped(json, false);
}

export function WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workflow {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': TypedOperatorOperatorFromJSON(json['operator']),
        'type': json['type'],
    };
}

export function WorkflowToJSON(value?: Workflow | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operator': TypedOperatorOperatorToJSON(value['operator']),
        'type': value['type'],
    };
}

