/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ColumnNames {
    ColumnNamesOneOf(Box<models::ColumnNamesOneOf>),
    ColumnNamesOneOf1(Box<models::ColumnNamesOneOf1>),
    ColumnNamesOneOf2(Box<models::ColumnNamesOneOf2>),
}

impl Default for ColumnNames {
    fn default() -> Self {
        Self::ColumnNamesOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "suffix")]
    Suffix,
    #[serde(rename = "names")]
    Names,
}

impl Default for Type {
    fn default() -> Type {
        Self::Default
    }
}

