/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GetFeatureRequest {
    #[serde(rename = "GetFeature")]
    GetFeature,

}

impl std::fmt::Display for GetFeatureRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GetFeature => write!(f, "GetFeature"),
        }
    }
}

impl Default for GetFeatureRequest {
    fn default() -> GetFeatureRequest {
        Self::GetFeature
    }
}

