/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistogramBoundsOneOf1 {
    #[serde(rename = "values")]
    pub values: Box<models::HistogramBoundsOneOf1Values>,
}

impl HistogramBoundsOneOf1 {
    pub fn new(values: models::HistogramBoundsOneOf1Values) -> HistogramBoundsOneOf1 {
        HistogramBoundsOneOf1 {
            values: Box::new(values),
        }
    }
}

