/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterpolationResolutionOneOf1 : Upscale factor relative to input resolution (`x >= 1`, `y >= 1`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterpolationResolutionOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
}

impl InterpolationResolutionOneOf1 {
    /// Upscale factor relative to input resolution (`x >= 1`, `y >= 1`).
    pub fn new(r#type: Type, x: f64, y: f64) -> InterpolationResolutionOneOf1 {
        InterpolationResolutionOneOf1 {
            r#type,
            x,
            y,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fraction")]
    Fraction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fraction
    }
}

