/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Measurement {
    #[serde(rename="unitless")]
    Unitless(models::UnitlessMeasurement),
    #[serde(rename="continuous")]
    Continuous(models::ContinuousMeasurement),
    #[serde(rename="classification")]
    Classification(models::ClassificationMeasurement),
}

impl Default for Measurement {
    fn default() -> Self {
        Self::Unitless(Default::default())
    }
}


