/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiPoint1 {
    #[serde(rename = "MultiPoint")]
    pub multi_point: Box<models::MultiPoint>,
}

impl MultiPoint1 {
    pub fn new(multi_point: models::MultiPoint) -> MultiPoint1 {
        MultiPoint1 {
            multi_point: Box::new(multi_point),
        }
    }
}

