/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlotQueryRectangle : A spatio-temporal rectangle with a specified resolution
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlotQueryRectangle {
    #[serde(rename = "spatialBounds")]
    pub spatial_bounds: Box<models::BoundingBox2D>,
    #[serde(rename = "spatialResolution")]
    pub spatial_resolution: Box<models::SpatialResolution>,
    #[serde(rename = "timeInterval")]
    pub time_interval: Box<models::TimeInterval>,
}

impl PlotQueryRectangle {
    /// A spatio-temporal rectangle with a specified resolution
    pub fn new(spatial_bounds: models::BoundingBox2D, spatial_resolution: models::SpatialResolution, time_interval: models::TimeInterval) -> PlotQueryRectangle {
        PlotQueryRectangle {
            spatial_bounds: Box::new(spatial_bounds),
            spatial_resolution: Box::new(spatial_resolution),
            time_interval: Box::new(time_interval),
        }
    }
}

