/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StacBand {
    #[serde(rename = "dataType")]
    pub data_type: models::RasterDataType,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "noDataValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub no_data_value: Option<Option<f64>>,
}

impl StacBand {
    pub fn new(data_type: models::RasterDataType, name: String) -> StacBand {
        StacBand {
            data_type,
            name,
            no_data_value: None,
        }
    }
}

