/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextSymbology {
    #[serde(rename = "attribute")]
    pub attribute: String,
    #[serde(rename = "fillColor")]
    pub fill_color: models::ColorParam,
    #[serde(rename = "stroke")]
    pub stroke: models::StrokeParam,
}

impl TextSymbology {
    pub fn new(attribute: String, fill_color: models::ColorParam, stroke: models::StrokeParam) -> TextSymbology {
        TextSymbology {
            attribute,
            fill_color,
            stroke,
        }
    }
}

