/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeDimensionOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TimeDimensionOneOf1 {
    pub fn new(r#type: Type) -> TimeDimensionOneOf1 {
        TimeDimensionOneOf1 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "irregular")]
    Irregular,
}

impl Default for Type {
    fn default() -> Type {
        Self::Irregular
    }
}

