/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypedOperatorOneOf {
    #[serde(rename = "operator")]
    pub operator: models::RasterOperator,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TypedOperatorOneOf {
    pub fn new(operator: models::RasterOperator, r#type: Type) -> TypedOperatorOneOf {
        TypedOperatorOneOf {
            operator,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Raster")]
    Raster,
}

impl Default for Type {
    fn default() -> Type {
        Self::Raster
    }
}

