/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TypedOperator : Operator outputs are distinguished by their data type. There are `raster`, `vector` and `plot` operators.
/// Operator outputs are distinguished by their data type. There are `raster`, `vector` and `plot` operators.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TypedOperator {
    TypedOperatorOneOf(Box<models::TypedOperatorOneOf>),
    TypedOperatorOneOf1(Box<models::TypedOperatorOneOf1>),
    TypedOperatorOneOf2(Box<models::TypedOperatorOneOf2>),
}

impl Default for TypedOperator {
    fn default() -> Self {
        Self::TypedOperatorOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Vector")]
    Vector,
    #[serde(rename = "Raster")]
    Raster,
    #[serde(rename = "Plot")]
    Plot,
}

impl Default for Type {
    fn default() -> Type {
        Self::Vector
    }
}

