/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TypedGeometry {
    TypedGeometryOneOf(models::TypedGeometryOneOf),
    TypedGeometryOneOf1(models::TypedGeometryOneOf1),
    TypedGeometryOneOf2(models::TypedGeometryOneOf2),
    TypedGeometryOneOf3(models::TypedGeometryOneOf3),
}

impl Default for TypedGeometry {
    fn default() -> Self {
        Self::TypedGeometryOneOf(Default::default())
    }
}

