/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TypedGeometry {
    NoGeometry1(Box<models::NoGeometry1>),
    MultiPoint1(Box<models::MultiPoint1>),
    MultiLineString1(Box<models::MultiLineString1>),
    MultiPolygon1(Box<models::MultiPolygon1>),
}

impl Default for TypedGeometry {
    fn default() -> Self {
        Self::NoGeometry1(Default::default())
    }
}

