/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypedGeometryOneOf2 {
    #[serde(rename = "MultiLineString")]
    pub multi_line_string: Box<models::MultiLineString>,
}

impl TypedGeometryOneOf2 {
    pub fn new(multi_line_string: models::MultiLineString) -> TypedGeometryOneOf2 {
        TypedGeometryOneOf2 {
            multi_line_string: Box::new(multi_line_string),
        }
    }
}

