/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TypedGeometry {
    TypedGeometryOneOf(Box<models::TypedGeometryOneOf>),
    TypedGeometryOneOf1(Box<models::TypedGeometryOneOf1>),
    TypedGeometryOneOf2(Box<models::TypedGeometryOneOf2>),
    TypedGeometryOneOf3(Box<models::TypedGeometryOneOf3>),
}

impl Default for TypedGeometry {
    fn default() -> Self {
        Self::TypedGeometryOneOf(Default::default())
    }
}

