inputSpec: .generation/input/openapi.json
outputDir: typescript
generatorName: typescript-fetch
gitHost: github.com
gitUserId: geo-engine
gitRepoId: openapi-client
additionalProperties:
    supportsES6: true
    npmName: "@geoengine/openapi-client"
    npmVersion: 0.0.32
openapiNormalizer:
    REF_AS_PARENT_IN_ALLOF: true