/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeoJson,
  WfsService,
  WfsVersion,
} from '../models/index';
import {
    GeoJsonFromJSON,
    GeoJsonToJSON,
    WfsServiceFromJSON,
    WfsServiceToJSON,
    WfsVersionFromJSON,
    WfsVersionToJSON,
} from '../models/index';

export interface WfsHandlerRequest {
    workflow: string;
    bbox: string;
    request: WfsHandlerRequestEnum;
    service: WfsService;
    typeNames: string;
    count?: number | null;
    filter?: string | null;
    namespaces?: string | null;
    propertyName?: string | null;
    resultType?: string | null;
    sortBy?: string | null;
    srsName?: string | null;
    time?: string;
    version?: WfsVersion | null;
}

/**
 * 
 */
export class OGCWFSApi extends runtime.BaseAPI {

    /**
     * OGC WFS endpoint
     */
    async wfsHandlerRaw(requestParameters: WfsHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeoJson>> {
        if (requestParameters['workflow'] == null) {
            throw new runtime.RequiredError(
                'workflow',
                'Required parameter "workflow" was null or undefined when calling wfsHandler().'
            );
        }

        if (requestParameters['bbox'] == null) {
            throw new runtime.RequiredError(
                'bbox',
                'Required parameter "bbox" was null or undefined when calling wfsHandler().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling wfsHandler().'
            );
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling wfsHandler().'
            );
        }

        if (requestParameters['typeNames'] == null) {
            throw new runtime.RequiredError(
                'typeNames',
                'Required parameter "typeNames" was null or undefined when calling wfsHandler().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['namespaces'] != null) {
            queryParameters['namespaces'] = requestParameters['namespaces'];
        }

        if (requestParameters['propertyName'] != null) {
            queryParameters['propertyName'] = requestParameters['propertyName'];
        }

        if (requestParameters['request'] != null) {
            queryParameters['request'] = requestParameters['request'];
        }

        if (requestParameters['resultType'] != null) {
            queryParameters['resultType'] = requestParameters['resultType'];
        }

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['srsName'] != null) {
            queryParameters['srsName'] = requestParameters['srsName'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = requestParameters['time'];
        }

        if (requestParameters['typeNames'] != null) {
            queryParameters['typeNames'] = requestParameters['typeNames'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wfs/{workflow}`;
        urlPath = urlPath.replace(`{${"workflow"}}`, encodeURIComponent(String(requestParameters['workflow'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeoJsonFromJSON(jsonValue));
    }

    /**
     * OGC WFS endpoint
     */
    async wfsHandler(requestParameters: WfsHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeoJson> {
        const response = await this.wfsHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const WfsHandlerRequestEnum = {
    GetCapabilities: 'GetCapabilities',
    GetFeature: 'GetFeature'
} as const;
export type WfsHandlerRequestEnum = typeof WfsHandlerRequestEnum[keyof typeof WfsHandlerRequestEnum];
