# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from uuid import UUID
from geoengine_openapi_client.models.get_capabilities_format import GetCapabilitiesFormat
from geoengine_openapi_client.models.get_map_exception_format import GetMapExceptionFormat
from geoengine_openapi_client.models.wms_service import WmsService
from geoengine_openapi_client.models.wms_version import WmsVersion

from geoengine_openapi_client.api_client import ApiClient, RequestSerialized
from geoengine_openapi_client.api_response import ApiResponse
from geoengine_openapi_client.rest import RESTResponseType


class OGCWMSApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def wms_handler(
        self,
        workflow: Annotated[UUID, Field(description="Workflow id")],
        bbox: StrictStr,
        bgcolor: Optional[StrictStr],
        crs: Optional[StrictStr],
        elevation: Optional[StrictStr],
        exceptions: Optional[GetMapExceptionFormat],
        format: Optional[GetCapabilitiesFormat],
        height: Annotated[int, Field(strict=True, ge=0)],
        info_format: Optional[StrictStr],
        layer: StrictStr,
        layers: StrictStr,
        query_layers: StrictStr,
        request: Annotated[StrictStr, Field(description="type of WMS request")],
        service: WmsService,
        sld: Optional[StrictStr],
        sld_body: Optional[StrictStr],
        styles: StrictStr,
        time: StrictStr,
        transparent: Optional[StrictBool],
        version: Optional[WmsVersion],
        width: Annotated[int, Field(strict=True, ge=0)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """OGC WMS endpoint


        :param workflow: Workflow id (required)
        :type workflow: str
        :param bbox: (required)
        :type bbox: str
        :param bgcolor: (required)
        :type bgcolor: str
        :param crs: (required)
        :type crs: str
        :param elevation: (required)
        :type elevation: str
        :param exceptions: (required)
        :type exceptions: GetMapExceptionFormat
        :param format: (required)
        :type format: GetCapabilitiesFormat
        :param height: (required)
        :type height: int
        :param info_format: (required)
        :type info_format: str
        :param layer: (required)
        :type layer: str
        :param layers: (required)
        :type layers: str
        :param query_layers: (required)
        :type query_layers: str
        :param request: type of WMS request (required)
        :type request: str
        :param service: (required)
        :type service: WmsService
        :param sld: (required)
        :type sld: str
        :param sld_body: (required)
        :type sld_body: str
        :param styles: (required)
        :type styles: str
        :param time: (required)
        :type time: str
        :param transparent: (required)
        :type transparent: bool
        :param version: (required)
        :type version: WmsVersion
        :param width: (required)
        :type width: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._wms_handler_serialize(
            workflow=workflow,
            bbox=bbox,
            bgcolor=bgcolor,
            crs=crs,
            elevation=elevation,
            exceptions=exceptions,
            format=format,
            height=height,
            info_format=info_format,
            layer=layer,
            layers=layers,
            query_layers=query_layers,
            request=request,
            service=service,
            sld=sld,
            sld_body=sld_body,
            styles=styles,
            time=time,
            transparent=transparent,
            version=version,
            width=width,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def wms_handler_with_http_info(
        self,
        workflow: Annotated[UUID, Field(description="Workflow id")],
        bbox: StrictStr,
        bgcolor: Optional[StrictStr],
        crs: Optional[StrictStr],
        elevation: Optional[StrictStr],
        exceptions: Optional[GetMapExceptionFormat],
        format: Optional[GetCapabilitiesFormat],
        height: Annotated[int, Field(strict=True, ge=0)],
        info_format: Optional[StrictStr],
        layer: StrictStr,
        layers: StrictStr,
        query_layers: StrictStr,
        request: Annotated[StrictStr, Field(description="type of WMS request")],
        service: WmsService,
        sld: Optional[StrictStr],
        sld_body: Optional[StrictStr],
        styles: StrictStr,
        time: StrictStr,
        transparent: Optional[StrictBool],
        version: Optional[WmsVersion],
        width: Annotated[int, Field(strict=True, ge=0)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """OGC WMS endpoint


        :param workflow: Workflow id (required)
        :type workflow: str
        :param bbox: (required)
        :type bbox: str
        :param bgcolor: (required)
        :type bgcolor: str
        :param crs: (required)
        :type crs: str
        :param elevation: (required)
        :type elevation: str
        :param exceptions: (required)
        :type exceptions: GetMapExceptionFormat
        :param format: (required)
        :type format: GetCapabilitiesFormat
        :param height: (required)
        :type height: int
        :param info_format: (required)
        :type info_format: str
        :param layer: (required)
        :type layer: str
        :param layers: (required)
        :type layers: str
        :param query_layers: (required)
        :type query_layers: str
        :param request: type of WMS request (required)
        :type request: str
        :param service: (required)
        :type service: WmsService
        :param sld: (required)
        :type sld: str
        :param sld_body: (required)
        :type sld_body: str
        :param styles: (required)
        :type styles: str
        :param time: (required)
        :type time: str
        :param transparent: (required)
        :type transparent: bool
        :param version: (required)
        :type version: WmsVersion
        :param width: (required)
        :type width: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._wms_handler_serialize(
            workflow=workflow,
            bbox=bbox,
            bgcolor=bgcolor,
            crs=crs,
            elevation=elevation,
            exceptions=exceptions,
            format=format,
            height=height,
            info_format=info_format,
            layer=layer,
            layers=layers,
            query_layers=query_layers,
            request=request,
            service=service,
            sld=sld,
            sld_body=sld_body,
            styles=styles,
            time=time,
            transparent=transparent,
            version=version,
            width=width,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def wms_handler_without_preload_content(
        self,
        workflow: Annotated[UUID, Field(description="Workflow id")],
        bbox: StrictStr,
        bgcolor: Optional[StrictStr],
        crs: Optional[StrictStr],
        elevation: Optional[StrictStr],
        exceptions: Optional[GetMapExceptionFormat],
        format: Optional[GetCapabilitiesFormat],
        height: Annotated[int, Field(strict=True, ge=0)],
        info_format: Optional[StrictStr],
        layer: StrictStr,
        layers: StrictStr,
        query_layers: StrictStr,
        request: Annotated[StrictStr, Field(description="type of WMS request")],
        service: WmsService,
        sld: Optional[StrictStr],
        sld_body: Optional[StrictStr],
        styles: StrictStr,
        time: StrictStr,
        transparent: Optional[StrictBool],
        version: Optional[WmsVersion],
        width: Annotated[int, Field(strict=True, ge=0)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """OGC WMS endpoint


        :param workflow: Workflow id (required)
        :type workflow: str
        :param bbox: (required)
        :type bbox: str
        :param bgcolor: (required)
        :type bgcolor: str
        :param crs: (required)
        :type crs: str
        :param elevation: (required)
        :type elevation: str
        :param exceptions: (required)
        :type exceptions: GetMapExceptionFormat
        :param format: (required)
        :type format: GetCapabilitiesFormat
        :param height: (required)
        :type height: int
        :param info_format: (required)
        :type info_format: str
        :param layer: (required)
        :type layer: str
        :param layers: (required)
        :type layers: str
        :param query_layers: (required)
        :type query_layers: str
        :param request: type of WMS request (required)
        :type request: str
        :param service: (required)
        :type service: WmsService
        :param sld: (required)
        :type sld: str
        :param sld_body: (required)
        :type sld_body: str
        :param styles: (required)
        :type styles: str
        :param time: (required)
        :type time: str
        :param transparent: (required)
        :type transparent: bool
        :param version: (required)
        :type version: WmsVersion
        :param width: (required)
        :type width: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._wms_handler_serialize(
            workflow=workflow,
            bbox=bbox,
            bgcolor=bgcolor,
            crs=crs,
            elevation=elevation,
            exceptions=exceptions,
            format=format,
            height=height,
            info_format=info_format,
            layer=layer,
            layers=layers,
            query_layers=query_layers,
            request=request,
            service=service,
            sld=sld,
            sld_body=sld_body,
            styles=styles,
            time=time,
            transparent=transparent,
            version=version,
            width=width,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _wms_handler_serialize(
        self,
        workflow,
        bbox,
        bgcolor,
        crs,
        elevation,
        exceptions,
        format,
        height,
        info_format,
        layer,
        layers,
        query_layers,
        request,
        service,
        sld,
        sld_body,
        styles,
        time,
        transparent,
        version,
        width,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if workflow is not None:
            _path_params['workflow'] = workflow
        if bbox is not None:
            _path_params['bbox'] = bbox
        if bgcolor is not None:
            _path_params['bgcolor'] = bgcolor
        if crs is not None:
            _path_params['crs'] = crs
        if elevation is not None:
            _path_params['elevation'] = elevation
        if exceptions is not None:
            _path_params['exceptions'] = exceptions.value
        if format is not None:
            _path_params['format'] = format.value
        if height is not None:
            _path_params['height'] = height
        if info_format is not None:
            _path_params['info_format'] = info_format
        if layer is not None:
            _path_params['layer'] = layer
        if layers is not None:
            _path_params['layers'] = layers
        if query_layers is not None:
            _path_params['query_layers'] = query_layers
        if request is not None:
            _path_params['request'] = request
        if service is not None:
            _path_params['service'] = service.value
        if sld is not None:
            _path_params['sld'] = sld
        if sld_body is not None:
            _path_params['sld_body'] = sld_body
        if styles is not None:
            _path_params['styles'] = styles
        if time is not None:
            _path_params['time'] = time
        if transparent is not None:
            _path_params['transparent'] = transparent
        if version is not None:
            _path_params['version'] = version.value
        if width is not None:
            _path_params['width'] = width
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'text/xml'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'session_token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/wms/{workflow}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


